### ISSUE TITLE
Figure out if pandoc can create anchors for the manpages

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc.github.io#20]
So we can link to them properly, for example `https://labwc.github.io/labwc-config.5.html#regions`.

Alternative: add another Python script to do the job.
- Create at least ids for the `<h2>` elements, possibly also for the `<strong>` ones.
- Potentially add a usually invisible hover permanent-link icon, similar to hovering over `labwc.github.io` [here](https://github.com/labwc/labwc.github.io/blob/main/README.md)
- Being extra fancy: highlight the current target via CSS

E.g. something like this, CSS additions to `src/template_pre.html`:
```css
a.perma {
       display: none;
}
a.perma:hover {
       text-decoration: none;
}
:hover > a.perma {
       width: 1.5em;
       margin-left: -1.5em;
       display: inline-block;
}
:target {
       background-color: rgba(128, 128, 128, 0.2);
}
```

```sh
./build-site
sed -i 's,<\(h[12]\)>\([^<]*\)</h[12]>,<\1 id="\2"><a class="perma" href="#\2">🔗</a>\2</\1>,' deploy/labwc-config.5.html
```
